setwd("/Users/yunluli/Desktop/stat5120/hw3")
data<-read.table("Senic.txt", header=TRUE,sep="")
attach(data)
plot(Stay, InfctRsk, main="InfctRsk Against Stay")
result<-lm(InfctRsk~Stay)
abline(result, col='red')
plot(result$fitted.values,result$residuals, xlab="Fitted Values", ylab="Residuals", main="Plot of Residuals vs Fits")
abline(h=0,col="red")

summary(result)

acf(result$residuals, main="Autocorrelation of Residuals")

data.sub<-subset(data,Stay<=15)
plot(data.sub$Stay, data.sub$InfctRsk, main="InfctRsk Against Stay")
result2<-lm(data.sub$InfctRsk~data.sub$Stay)
abline(result2, col='red')
plot(result2$fitted.values,result2$residuals, xlab="Fitted Values", ylab="Residuals", main="Plot of Residuals vs Fits")
acf(result2$residuals, main="Autocorrelation of Residuals")
qqnorm(result2$residuals,main="Normal Probability Plot of Residuals")
qqline(result2$residuals, col="red")
summary(result2)
anova(result2)

sol<-read.table("solution.txt", header=FALSE,sep="")
colnames(sol)<-c("Y","X")
attach(sol)
plot(X, Y, xlab="time", ylab="concentrations", main="Concentration Against Time")
res<-lm(Y~X)
abline(res, col='red')
summary(res)
plot(res$fitted.values,res$residuals, xlab="Fitted Values", ylab="Residuals", main="Plot of Residuals vs Fits")
abline(h=0,col="red")
library(MASS) ##boxcox function in MASS package.
boxcox(res)

log.y<-log(Y)
res.log<-lm(log.y~X)
summary(res.log)
plot(X, log.y, xlab="time", ylab=" log concentrations", main="Log Concentration Against Time")
abline(res.log, col='red')
plot(res.log$fitted.values,res.log$residuals, xlab="Fitted Values", ylab="Residuals", main="Plot of Residuals vs Fits")
abline(h=0,col="red")

reduced<-lm(log.y~X)
full<-lm(log.y~0+as.factor(X))
anova(reduced,full)

data<-read.table("coffeeshop.txt", header=FALSE, sep="")
colnames(data)<-c("Rating","Number_of_Likes","Number_of_Photos")
attach(data)
log.like<-log(Number_of_Likes)
plot(log.like, Rating,  main="Rating Against Log # of Likes")
lr<-lm(Rating~log.like)
abline(lr, col='red')
plot(lr$fitted.values,lr$residuals, xlab="Fitted Values", ylab="Residuals", main="Plot of Residuals vs Fits")
abline(h=0,col="red")

new <- data.frame(log.like=log(100)) ##For 100 number of likes, the input to the loglog model should be log(100)
prd<-predict.lm(lr,new,interval="prediction")
prd

ratings.trans<--log(10-Rating)
plot(log.like, ratings.trans,  main="Transformed Rating Against Log # of Likes")
lr2<-lm(ratings.trans~log.like)
abline(lr2, col='red')
plot(lr2$fitted.values,lr2$residuals, xlab="Fitted Values", ylab="Residuals", main="Plot of Residuals vs Fits")
abline(h=0,col="red")
prd2
prd2<-predict.lm(lr2,new,interval="prediction")
10-exp(-prd2)

qf(0.95,19,99)
qf(0.95,1,118)
