getwd()
setwd("/Users/yunluli/Desktop/stat5120/hw2")
data<-read.table("Copier.txt", header=TRUE, sep="")
attach(data)
plot(Serviced, Minutes, xlab="Number of Copiers Serviced", ylab="Total Number of Minutes", main="Plot of Minutes against Serviced")
result=lm(Minutes~Serviced)
summary(result)
confint(result,level = 0.95)
anova(result)
newdata<-data.frame(Serviced=5)
predict.lm(result, newdata, interval="confidence", level=0.95)
